import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const server=fs.readFileSync('server/src/index.js','utf8');
const migrate=fs.readFileSync('server/src/migrate.js','utf8');
const ui=fs.readFileSync('dashboard/public/app.js','utf8');
const html=fs.readFileSync('dashboard/public/index.html','utf8');
test('persistent web policy tables and exception mapping exist',()=>{assert.match(migrate,/CREATE TABLE IF NOT EXISTS web_policies/);assert.match(migrate,/web_policy_staff_exceptions/);});
test('mass policy API stores exact set and fans out without closing browser',()=>{assert.match(server,/app\.put\('\/api\/web-policy'/);assert.match(server,/fanoutWebPolicy/);assert.match(server,/closeBrowser:false/);assert.match(server,/persistent:true/);});
test('policy supports per-staff exception and agent heartbeat snapshot',()=>{assert.match(server,/device_shift_assignments/);assert.match(server,/webPolicy/);assert.match(server,/exempt/);});
test('dashboard has web policy control surface',()=>{assert.match(html,/Web Policy Full-Time/);assert.match(html,/policyStaffList/);assert.match(ui,/saveWebPolicy/);assert.match(ui,/policyReapplyBtn/);});
