import 'dotenv/config';
import express from 'express';
import http from 'http';
import helmet from 'helmet';
import cors from 'cors';
import rateLimit from 'express-rate-limit';
import { Server } from 'socket.io';
import crypto from 'crypto';
import { z } from 'zod';
import { q, pool } from './db.js';
import { login, requireAuth, requireRole, officeSql } from './auth.js';

const app=express(); const server=http.createServer(app); const io=new Server(server,{cors:{origin:true,credentials:false}});
app.use(helmet({contentSecurityPolicy:false})); app.use(cors()); app.use(express.json({limit:'5mb'}));
app.use('/api/auth',rateLimit({windowMs:15*60*1000,limit:60}));
app.use(express.static(new URL('../../dashboard/public',import.meta.url).pathname));
const asyncH=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
const audit=async(req,action,target,detail={})=>{try{await q('INSERT INTO audit_logs(user_id,action,target,ip,detail) VALUES($1,$2,$3,$4,$5)',[req.user?.sub||null,action,target,req.ip,detail]);}catch{}};
const canOffice=(user,officeId)=>user.role==='SUPER_ADMIN'||!user.officeId||user.officeId===officeId;
const liveFrames=new Map();
let fleetChangeTimer=null;
const pendingFleetDeviceIds=new Set();
function queueFleetChange(deviceId){
  if(deviceId)pendingFleetDeviceIds.add(deviceId);
  if(fleetChangeTimer)return;
  fleetChangeTimer=setTimeout(()=>{
    fleetChangeTimer=null;
    const deviceIds=[...pendingFleetDeviceIds];
    pendingFleetDeviceIds.clear();
    io.emit('fleet.changed',{deviceIds});
  },1500);
  fleetChangeTimer.unref?.();
}

app.get('/health',asyncH(async(req,res)=>{const db=await q('SELECT 1 ok');const c=await q("SELECT count(*)::int n FROM devices WHERE (COALESCE(user_last_seen,last_seen)>now()-interval '180 seconds' OR system_last_seen>now()-interval '180 seconds') AND disabled=false");res.json({ok:true,api:'OK',database:db.rows[0].ok===1?'OK':'ERROR',realtime:'OK',connectedAgents:c.rows[0].n});}));
app.post('/api/auth/login',asyncH(async(req,res)=>{const s=z.object({loginId:z.string().min(1).max(100),password:z.string().min(1).max(200)}).parse(req.body);const out=await login(s.loginId,s.password);if(!out)return res.status(401).json({ok:false,error:'ID atau password salah'});res.json({ok:true,...out});}));

function makeToken(){return crypto.randomBytes(32).toString('hex')}
function tokenHash(t){return crypto.createHash('sha256').update(t).digest('hex')}
async function deviceAuth(req,res,next){
 const uid=req.headers['x-device-id'],token=req.headers['x-device-token'];if(!uid||!token)return res.status(401).json({ok:false,error:'Device auth required'});
 const r=await q(`SELECT d.* FROM devices d JOIN device_tokens t ON t.device_id=d.id WHERE d.device_uid=$1 AND t.token_hash=$2 AND t.revoked_at IS NULL AND d.disabled=false ORDER BY t.created_at DESC LIMIT 1`,[String(uid),tokenHash(String(token))]);
 if(!r.rows[0])return res.status(401).json({ok:false,error:'Device token invalid'});req.device=r.rows[0];next();
}
app.post('/api/agent/enroll',asyncH(async(req,res)=>{
 if(req.headers['x-enroll-secret']!==process.env.DEVICE_ENROLL_SECRET)return res.status(401).json({ok:false,error:'Enroll secret invalid'});
 const s=z.object({deviceUid:z.string().min(8).max(200),hardwareUid:z.string().min(8).max(200).optional(),name:z.string().min(1).max(200),os:z.string().max(200).optional(),agentVersion:z.string().max(50).optional(),officeName:z.string().max(200).optional()}).parse(req.body);
 let officeId=null;if(s.officeName){const o=await q('SELECT id FROM offices WHERE lower(name)=lower($1) AND active=true',[s.officeName]);officeId=o.rows[0]?.id||null;}
 const revoked=await q('SELECT 1 FROM revoked_devices WHERE device_uid=$1',[s.deviceUid]);if(revoked.rows[0])return res.status(403).json({ok:false,error:'Device revoked'});
 let existing=await q('SELECT id,device_uid,name,office_id,hardware_uid FROM devices WHERE device_uid=$1',[s.deviceUid]);
 if(!existing.rows[0]&&s.hardwareUid)existing=await q('SELECT id,device_uid,name,office_id,hardware_uid FROM devices WHERE hardware_uid=$1 AND disabled=false ORDER BY enrolled_at LIMIT 1',[s.hardwareUid]);
 let d;if(existing.rows[0]){d=await q(`UPDATE devices SET name=$2,os=$3,agent_version=$4,office_id=COALESCE(office_id,$5),hardware_uid=COALESCE(hardware_uid,$6),system_last_seen=now(),disabled=false WHERE id=$1 RETURNING *`,[existing.rows[0].id,s.name,s.os||null,s.agentVersion||null,officeId,s.hardwareUid||null]);}
 else{d=await q(`INSERT INTO devices(device_uid,hardware_uid,name,os,agent_version,office_id,status,system_last_seen) VALUES($1,$2,$3,$4,$5,$6,'ONLINE',now()) RETURNING *`,[s.deviceUid,s.hardwareUid||null,s.name,s.os||null,s.agentVersion||null,officeId]);}
 const token=makeToken();await q('UPDATE device_tokens SET revoked_at=now() WHERE device_id=$1 AND revoked_at IS NULL',[d.rows[0].id]);await q('INSERT INTO device_tokens(device_id,token_hash) VALUES($1,$2)',[d.rows[0].id,tokenHash(token)]);res.json({ok:true,deviceId:d.rows[0].id,deviceUid:d.rows[0].device_uid,deviceToken:token});
}));
app.post('/api/agent/system-heartbeat',deviceAuth,asyncH(async(req,res)=>{const x=z.object({os:z.string().max(200).optional(),agentVersion:z.string().max(50).optional()}).parse(req.body||{});await q(`UPDATE devices SET os=COALESCE($1,os),agent_version=COALESCE($2,agent_version),ip=$3,system_last_seen=now() WHERE id=$4`,[x.os||null,x.agentVersion||null,req.ip.replace('::ffff:',''),req.device.id]);queueFleetChange(req.device.id);res.json({ok:true});}));
app.post('/api/agent/heartbeat',deviceAuth,asyncH(async(req,res)=>{
 const s=z.object({status:z.enum(['ONLINE','ACTIVE','IDLE','LOCKED']).default('ONLINE'),currentApp:z.string().max(300).nullable().optional(),currentTitle:z.string().max(500).nullable().optional(),os:z.string().max(200).optional(),agentVersion:z.string().max(50).optional()}).parse(req.body||{});
 await q('UPDATE devices SET status=$1,current_app=$2,current_title=$3,os=COALESCE($4,os),agent_version=COALESCE($5,agent_version),ip=$6,last_seen=now(),user_last_seen=now() WHERE id=$7',[s.status,s.currentApp||null,s.currentTitle||null,s.os||null,s.agentVersion||null,req.ip.replace('::ffff:',''),req.device.id]);
 io.to(`device:${req.device.id}`).emit('device.status',{deviceId:req.device.id,...s,lastSeen:new Date().toISOString()});queueFleetChange(req.device.id);
 const cmds=await q("SELECT id,command_type,payload,created_at FROM commands WHERE device_id=$1 AND status='PENDING' ORDER BY created_at LIMIT 10",[req.device.id]);if(cmds.rows.length)await q("UPDATE commands SET status='SENT' WHERE id = ANY($1::uuid[])",[cmds.rows.map(x=>x.id)]);res.json({ok:true,commands:cmds.rows});
}));
app.post('/api/agent/activity',deviceAuth,asyncH(async(req,res)=>{
 const s=z.object({occurredAt:z.string().datetime().optional(),eventType:z.string().min(1).max(50),appName:z.string().max(300).optional(),processName:z.string().max(300).optional(),windowTitle:z.string().max(500).optional(),durationSeconds:z.number().int().nonnegative().optional()}).parse(req.body);
 const ts=s.occurredAt||new Date().toISOString();await q('INSERT INTO activity_events(device_id,occurred_at,event_type,app_name,process_name,window_title,duration_seconds) VALUES($1,$2,$3,$4,$5,$6,$7)',[req.device.id,ts,s.eventType,s.appName||null,s.processName||null,s.windowTitle||null,s.durationSeconds||null]);await q('UPDATE devices SET current_app=$1,current_title=$2,status=$3,last_seen=now(),user_last_seen=now() WHERE id=$4',[s.appName||null,s.windowTitle||null,s.eventType==='IDLE'?'IDLE':s.eventType==='LOCKED'?'LOCKED':'ACTIVE',req.device.id]);io.emit('device.activity',{deviceId:req.device.id,...s});res.json({ok:true});
}));
app.post('/api/agent/commands/:id/ack',deviceAuth,asyncH(async(req,res)=>{const s=z.object({ok:z.boolean(),result:z.string().max(2000).optional()}).parse(req.body);await q('UPDATE commands SET status=$1,ack_at=now(),result=$2 WHERE id=$3 AND device_id=$4',[s.ok?'ACK':'FAILED',s.result||null,req.params.id,req.device.id]);res.json({ok:true});}));
app.get('/api/agent/commands',deviceAuth,asyncH(async(req,res)=>{const cmds=await q("SELECT id,command_type,payload,created_at FROM commands WHERE device_id=$1 AND status='PENDING' ORDER BY created_at LIMIT 10",[req.device.id]);if(cmds.rows.length)await q("UPDATE commands SET status='SENT' WHERE id = ANY($1::uuid[])",[cmds.rows.map(x=>x.id)]);res.json({ok:true,commands:cmds.rows});}));
app.get('/api/agent/live-state',deviceAuth,asyncH(async(req,res)=>{const r=await q(`SELECT active,session_id,expires_at FROM live_sessions WHERE device_id=$1`,[req.device.id]);const row=r.rows[0];const active=!!row?.active&&!!row?.session_id&&(!row.expires_at||new Date(row.expires_at).getTime()>Date.now());if(row?.active&&!active)await q('UPDATE live_sessions SET active=false WHERE device_id=$1',[req.device.id]);res.set('Cache-Control','no-store').json({ok:true,active,sessionId:active?row.session_id:null,intervalMs:900,expiresAt:active?row.expires_at:null});}));
app.post('/api/agent/live-frame',deviceAuth,asyncH(async(req,res)=>{const x=z.object({sessionId:z.string().min(8).max(100),jpegBase64:z.string().min(100).max(4800000),width:z.number().int().positive().max(10000),height:z.number().int().positive().max(10000),capturedAt:z.string().optional()}).parse(req.body);const state=await q(`SELECT active,session_id,expires_at FROM live_sessions WHERE device_id=$1`,[req.device.id]);const row=state.rows[0];const valid=!!row?.active&&row.session_id===x.sessionId&&(!row.expires_at||new Date(row.expires_at).getTime()>Date.now());if(!valid)return res.status(409).json({ok:false,error:'Live view inactive or session changed'});liveFrames.set(req.device.id,{...x,receivedAt:Date.now()});res.json({ok:true});}));

app.get('/api/me',requireAuth,(req,res)=>res.json({ok:true,user:req.user}));
app.get('/api/offices',requireAuth,asyncH(async(req,res)=>{let r;if(req.user.role==='SUPER_ADMIN'||!req.user.officeId)r=await q('SELECT * FROM offices ORDER BY active DESC,name');else r=await q('SELECT * FROM offices WHERE id=$1',[req.user.officeId]);res.json({ok:true,items:r.rows});}));
app.post('/api/offices',requireAuth,requireRole('SUPER_ADMIN'),asyncH(async(req,res)=>{const s=z.object({name:z.string().trim().min(2).max(100)}).parse(req.body);const r=await q('INSERT INTO offices(name) VALUES($1) RETURNING *',[s.name]);await audit(req,'CREATE_OFFICE',s.name);res.json({ok:true,item:r.rows[0]});}));
app.patch('/api/offices/:id',requireAuth,requireRole('SUPER_ADMIN'),asyncH(async(req,res)=>{const s=z.object({name:z.string().trim().min(2).max(100).optional(),active:z.boolean().optional()}).parse(req.body);const old=await q('SELECT * FROM offices WHERE id=$1',[req.params.id]);if(!old.rows[0])return res.status(404).json({ok:false,error:'Kantor tidak ditemukan'});const r=await q('UPDATE offices SET name=COALESCE($1,name),active=COALESCE($2,active) WHERE id=$3 RETURNING *',[s.name??null,s.active??null,req.params.id]);await audit(req,'UPDATE_OFFICE',old.rows[0].name,{before:old.rows[0],after:r.rows[0]});res.json({ok:true,item:r.rows[0]});}));

app.get('/api/dashboard',requireAuth,asyncH(async(req,res)=>{const o=officeSql(req.user,'d');const r=await q(`SELECT count(*)::int total,count(*) FILTER(WHERE COALESCE(d.user_last_seen,d.last_seen)>now()-interval '180 seconds' OR d.system_last_seen>now()-interval '180 seconds')::int online,count(*) FILTER(WHERE d.status='ACTIVE' AND COALESCE(d.user_last_seen,d.last_seen)>now()-interval '180 seconds')::int active,count(*) FILTER(WHERE d.status='IDLE' AND COALESCE(d.user_last_seen,d.last_seen)>now()-interval '180 seconds')::int idle FROM devices d WHERE d.disabled=false ${o.clause}`,o.params);res.json({ok:true,...r.rows[0]});}));
const deviceSelect=`SELECT d.*,o.name office_name,
 mp.staff_id morning_staff_id,ms.name morning_staff_name,ms.staff_code morning_staff_code,
 np.staff_id night_staff_id,ns.name night_staff_name,ns.staff_code night_staff_code,
 CASE WHEN COALESCE(d.user_last_seen,d.last_seen)>now()-interval '180 seconds' THEN d.status WHEN d.system_last_seen>now()-interval '180 seconds' THEN 'SYSTEM_ONLY' ELSE 'OFFLINE' END effective_status,
 GREATEST(COALESCE(d.user_last_seen,d.last_seen), d.system_last_seen) effective_last_seen
 FROM devices d LEFT JOIN offices o ON o.id=d.office_id
 LEFT JOIN device_shift_assignments mp ON mp.device_id=d.id AND mp.shift='PAGI' LEFT JOIN staff ms ON ms.id=mp.staff_id
 LEFT JOIN device_shift_assignments np ON np.device_id=d.id AND np.shift='MALAM' LEFT JOIN staff ns ON ns.id=np.staff_id`;
app.get('/api/devices',requireAuth,asyncH(async(req,res)=>{const o=officeSql(req.user,'d');const r=await q(`${deviceSelect} WHERE d.disabled=false ${o.clause} ORDER BY d.name LIMIT 1000`,o.params);res.json({ok:true,items:r.rows});}));
app.get('/api/devices/:id',requireAuth,asyncH(async(req,res)=>{const r=await q(`${deviceSelect} WHERE d.id=$1`,[req.params.id]);if(!r.rows[0])return res.status(404).json({ok:false,error:'Device tidak ditemukan'});if(!canOffice(req.user,r.rows[0].office_id))return res.status(403).json({ok:false,error:'Forbidden'});res.json({ok:true,item:r.rows[0]});}));
app.patch('/api/devices/:id',requireAuth,requireRole('SUPER_ADMIN','ADMIN'),asyncH(async(req,res)=>{const s=z.object({name:z.string().trim().min(1).max(200).optional(),officeId:z.string().uuid().nullable().optional()}).parse(req.body);const d=await q('SELECT * FROM devices WHERE id=$1',[req.params.id]);if(!d.rows[0])return res.status(404).json({ok:false,error:'Device tidak ditemukan'});const targetOffice=s.officeId===undefined?d.rows[0].office_id:s.officeId;if(targetOffice&&!canOffice(req.user,targetOffice))return res.status(403).json({ok:false,error:'Forbidden'});if(s.officeId){const o=await q('SELECT id FROM offices WHERE id=$1 AND active=true',[s.officeId]);if(!o.rows[0])return res.status(400).json({ok:false,error:'Kantor tidak aktif/tidak ditemukan'});}const r=await q('UPDATE devices SET name=COALESCE($1,name),office_id=$2 WHERE id=$3 RETURNING *',[s.name??null,targetOffice,req.params.id]);if(s.officeId!==undefined&&s.officeId!==d.rows[0].office_id){await q('DELETE FROM device_shift_assignments WHERE device_id=$1',[req.params.id]);await q('UPDATE devices SET staff_id=NULL WHERE id=$1',[req.params.id]);}await audit(req,'UPDATE_DEVICE',d.rows[0].name,{name:r.rows[0].name,officeId:targetOffice});io.emit('fleet.changed',{deviceId:req.params.id});res.json({ok:true,item:r.rows[0]});}));
app.put('/api/devices/:id/shifts',requireAuth,requireRole('SUPER_ADMIN','ADMIN'),asyncH(async(req,res)=>{const s=z.object({morningStaffId:z.string().uuid().nullable(),nightStaffId:z.string().uuid().nullable()}).parse(req.body);const d=await q('SELECT * FROM devices WHERE id=$1',[req.params.id]);if(!d.rows[0])return res.status(404).json({ok:false,error:'Device tidak ditemukan'});if(d.rows[0].office_id&&!canOffice(req.user,d.rows[0].office_id))return res.status(403).json({ok:false,error:'Forbidden'});for(const [shift,id] of [['PAGI',s.morningStaffId],['MALAM',s.nightStaffId]]){if(id){const st=await q('SELECT id,office_id,active FROM staff WHERE id=$1',[id]);if(!st.rows[0]||!st.rows[0].active)return res.status(400).json({ok:false,error:`Staff ${shift} tidak valid`});if(d.rows[0].office_id&&st.rows[0].office_id!==d.rows[0].office_id)return res.status(400).json({ok:false,error:`Staff ${shift} harus dari kantor yang sama dengan PC`});}await q(`INSERT INTO device_shift_assignments(device_id,shift,staff_id,updated_at) VALUES($1,$2,$3,now()) ON CONFLICT(device_id,shift) DO UPDATE SET staff_id=excluded.staff_id,updated_at=now()`,[req.params.id,shift,id]);}await q('UPDATE devices SET staff_id=COALESCE($1,$2) WHERE id=$3',[s.morningStaffId,s.nightStaffId,req.params.id]);await audit(req,'ASSIGN_DEVICE_SHIFTS',d.rows[0].name,{morningStaffId:s.morningStaffId,nightStaffId:s.nightStaffId});io.emit('fleet.changed',{deviceId:req.params.id});res.json({ok:true});}));

app.put('/api/devices/:id/config',requireAuth,requireRole('SUPER_ADMIN','ADMIN'),asyncH(async(req,res)=>{
 const s=z.object({name:z.string().trim().min(1).max(200),officeId:z.string().uuid().nullable(),morningStaffId:z.string().uuid().nullable(),nightStaffId:z.string().uuid().nullable()}).parse(req.body);
 const client=await pool.connect();let old;
 try{
  await client.query('BEGIN');
  const d=await client.query('SELECT * FROM devices WHERE id=$1 FOR UPDATE',[req.params.id]);old=d.rows[0];
  if(!old){await client.query('ROLLBACK');return res.status(404).json({ok:false,error:'Device tidak ditemukan'});}
  if(old.office_id&&!canOffice(req.user,old.office_id)){await client.query('ROLLBACK');return res.status(403).json({ok:false,error:'Forbidden'});}
  if(s.officeId&&!canOffice(req.user,s.officeId)){await client.query('ROLLBACK');return res.status(403).json({ok:false,error:'Forbidden'});}
  if(s.officeId){const o=await client.query('SELECT id FROM offices WHERE id=$1 AND active=true',[s.officeId]);if(!o.rows[0]){await client.query('ROLLBACK');return res.status(400).json({ok:false,error:'Kantor tidak aktif/tidak ditemukan'});}}
  if(!s.officeId&&(s.morningStaffId||s.nightStaffId)){await client.query('ROLLBACK');return res.status(400).json({ok:false,error:'Pilih kantor terlebih dahulu sebelum memilih staff shift'});}
  for(const [shift,id] of [['PAGI',s.morningStaffId],['MALAM',s.nightStaffId]]){
   if(!id)continue;
   const st=await client.query('SELECT id,office_id,active FROM staff WHERE id=$1',[id]);
   if(!st.rows[0]||!st.rows[0].active){await client.query('ROLLBACK');return res.status(400).json({ok:false,error:`Staff ${shift} tidak valid/nonaktif`});}
   if(st.rows[0].office_id!==s.officeId){await client.query('ROLLBACK');return res.status(400).json({ok:false,error:`Staff ${shift} harus dari kantor yang sama dengan PC`});}
  }
  await client.query('UPDATE devices SET name=$1,office_id=$2,staff_id=COALESCE($3,$4) WHERE id=$5',[s.name,s.officeId,s.morningStaffId,s.nightStaffId,req.params.id]);
  for(const [shift,id] of [['PAGI',s.morningStaffId],['MALAM',s.nightStaffId]]){
   await client.query(`INSERT INTO device_shift_assignments(device_id,shift,staff_id,updated_at) VALUES($1,$2,$3,now()) ON CONFLICT(device_id,shift) DO UPDATE SET staff_id=excluded.staff_id,updated_at=now()`,[req.params.id,shift,id]);
  }
  await client.query('COMMIT');
 }catch(e){try{await client.query('ROLLBACK')}catch{};throw e}finally{client.release()}
 await audit(req,'UPDATE_DEVICE_CONFIG',old.name,{name:s.name,officeId:s.officeId,morningStaffId:s.morningStaffId,nightStaffId:s.nightStaffId});
 io.emit('fleet.changed',{deviceIds:[req.params.id],configChanged:true});
 res.json({ok:true});
}));
app.get('/api/devices/:id/activity',requireAuth,asyncH(async(req,res)=>{const d=await q('SELECT office_id FROM devices WHERE id=$1',[req.params.id]);if(!d.rows[0])return res.status(404).json({ok:false,error:'Device not found'});if(!canOffice(req.user,d.rows[0].office_id))return res.status(403).json({ok:false,error:'Forbidden'});const r=await q("SELECT * FROM activity_events WHERE device_id=$1 AND occurred_at>now()-interval '7 days' ORDER BY occurred_at DESC LIMIT 1000",[req.params.id]);res.json({ok:true,items:r.rows});}));
app.post('/api/devices/:id/command',requireAuth,requireRole('SUPER_ADMIN','ADMIN','SUPERVISOR'),asyncH(async(req,res)=>{const s=z.object({type:z.enum(['WARN','CLOSE_APP','SET_POLICY','BLOCK_DOMAIN','UNBLOCK_DOMAIN','BLOCK_DOMAINS','UNBLOCK_DOMAINS']),payload:z.record(z.string(),z.any()).default({})}).parse(req.body);const d=await q('SELECT office_id,name FROM devices WHERE id=$1',[req.params.id]);if(!d.rows[0])return res.status(404).json({ok:false,error:'Device not found'});if(!canOffice(req.user,d.rows[0].office_id))return res.status(403).json({ok:false,error:'Forbidden'});const c=await q('INSERT INTO commands(device_id,command_type,payload,created_by) VALUES($1,$2,$3,$4) RETURNING *',[req.params.id,s.type,s.payload,req.user.sub]);await audit(req,'CREATE_COMMAND',d.rows[0].name,{type:s.type,payload:s.payload});res.json({ok:true,command:c.rows[0]});}));


app.post('/api/devices/:id/live/start',requireAuth,requireRole('SUPER_ADMIN','ADMIN','SUPERVISOR'),asyncH(async(req,res)=>{const d=await q('SELECT office_id,name,last_seen,user_last_seen FROM devices WHERE id=$1 AND disabled=false',[req.params.id]);if(!d.rows[0])return res.status(404).json({ok:false,error:'Device not found'});if(!canOffice(req.user,d.rows[0].office_id))return res.status(403).json({ok:false,error:'Forbidden'});if(!d.rows[0].user_last_seen||Date.now()-new Date(d.rows[0].user_last_seen).getTime()>150000)return res.status(409).json({ok:false,error:'User agent belum aktif. Login ke Windows atau reinstall/update agent v2.0.0.'});const sessionId=crypto.randomBytes(16).toString('hex');liveFrames.delete(req.params.id);await q(`INSERT INTO live_sessions(device_id,active,requested_by,updated_at,session_id,expires_at) VALUES($1,true,$2,now(),$3,now()+interval '10 minutes') ON CONFLICT(device_id) DO UPDATE SET active=true,requested_by=$2,updated_at=now(),session_id=$3,expires_at=now()+interval '10 minutes'`,[req.params.id,req.user.sub,sessionId]);await audit(req,'LIVE_VIEW_START',d.rows[0].name,{sessionId});res.json({ok:true,sessionId,expiresInSeconds:600});}));
app.post('/api/devices/:id/live/stop',requireAuth,requireRole('SUPER_ADMIN','ADMIN','SUPERVISOR'),asyncH(async(req,res)=>{const d=await q('SELECT office_id,name FROM devices WHERE id=$1',[req.params.id]);if(!d.rows[0])return res.status(404).json({ok:false,error:'Device not found'});if(!canOffice(req.user,d.rows[0].office_id))return res.status(403).json({ok:false,error:'Forbidden'});await q('UPDATE live_sessions SET active=false,session_id=NULL,expires_at=NULL,updated_at=now() WHERE device_id=$1',[req.params.id]);liveFrames.delete(req.params.id);await audit(req,'LIVE_VIEW_STOP',d.rows[0].name);res.json({ok:true});}));
app.get('/api/devices/:id/live/frame',requireAuth,requireRole('SUPER_ADMIN','ADMIN','SUPERVISOR'),asyncH(async(req,res)=>{const d=await q('SELECT office_id FROM devices WHERE id=$1',[req.params.id]);if(!d.rows[0])return res.status(404).json({ok:false,error:'Device not found'});if(!canOffice(req.user,d.rows[0].office_id))return res.status(403).json({ok:false,error:'Forbidden'});const st=await q('SELECT active,session_id,expires_at FROM live_sessions WHERE device_id=$1',[req.params.id]);const row=st.rows[0];const active=!!row?.active&&!!row?.session_id&&(!row.expires_at||new Date(row.expires_at).getTime()>Date.now());if(!active)return res.status(204).end();const f=liveFrames.get(req.params.id);if(!f||f.sessionId!==row.session_id||Date.now()-f.receivedAt>8000)return res.status(204).end();res.set('Cache-Control','no-store').json({ok:true,frame:f});}));
app.delete('/api/devices/:id',requireAuth,requireRole('SUPER_ADMIN'),asyncH(async(req,res)=>{const mode=String(req.query.mode||'revoke');const d=await q('SELECT * FROM devices WHERE id=$1',[req.params.id]);if(!d.rows[0])return res.status(404).json({ok:false,error:'Device not found'});await q('INSERT INTO revoked_devices(device_uid,reason) VALUES($1,$2) ON CONFLICT(device_uid) DO UPDATE SET revoked_at=now(),reason=excluded.reason',[d.rows[0].device_uid,'Deleted from dashboard']);if(mode==='purge'){await q('DELETE FROM devices WHERE id=$1',[req.params.id])}else{await q('UPDATE device_tokens SET revoked_at=now() WHERE device_id=$1 AND revoked_at IS NULL',[req.params.id]);await q("UPDATE devices SET disabled=true,status='OFFLINE' WHERE id=$1",[req.params.id]);}liveFrames.delete(req.params.id);await audit(req,mode==='purge'?'DELETE_DEVICE_PURGE':'REVOKE_DEVICE',d.rows[0].name,{deviceUid:d.rows[0].device_uid});io.emit('fleet.changed',{});res.json({ok:true});}));
app.post('/api/devices/:id/reallow',requireAuth,requireRole('SUPER_ADMIN'),asyncH(async(req,res)=>{const d=await q('SELECT * FROM devices WHERE id=$1',[req.params.id]);if(!d.rows[0])return res.status(404).json({ok:false,error:'Device not found'});await q('DELETE FROM revoked_devices WHERE device_uid=$1',[d.rows[0].device_uid]);await q('UPDATE devices SET disabled=false WHERE id=$1',[req.params.id]);await audit(req,'REALLOW_DEVICE',d.rows[0].name);res.json({ok:true});}));

app.get('/api/staff',requireAuth,asyncH(async(req,res)=>{const params=[];let where='';if(req.user.role!=='SUPER_ADMIN'&&req.user.officeId){params.push(req.user.officeId);where='WHERE s.office_id=$1';}const r=await q(`SELECT s.*,o.name office_name,d.name department_name FROM staff s JOIN offices o ON o.id=s.office_id LEFT JOIN departments d ON d.id=s.department_id ${where} ORDER BY s.active DESC,s.name`,params);res.json({ok:true,items:r.rows});}));
app.post('/api/staff',requireAuth,requireRole('SUPER_ADMIN','ADMIN'),asyncH(async(req,res)=>{const s=z.object({staffCode:z.string().trim().min(1).max(80),name:z.string().trim().min(1).max(200),officeId:z.string().uuid(),departmentId:z.string().uuid().nullable().optional()}).parse(req.body);if(!canOffice(req.user,s.officeId))return res.status(403).json({ok:false,error:'Forbidden'});const r=await q('INSERT INTO staff(staff_code,name,office_id,department_id) VALUES($1,$2,$3,$4) RETURNING *',[s.staffCode,s.name,s.officeId,s.departmentId||null]);await audit(req,'CREATE_STAFF',s.staffCode);res.json({ok:true,item:r.rows[0]});}));
app.patch('/api/staff/:id',requireAuth,requireRole('SUPER_ADMIN','ADMIN'),asyncH(async(req,res)=>{const s=z.object({staffCode:z.string().trim().min(1).max(80).optional(),name:z.string().trim().min(1).max(200).optional(),officeId:z.string().uuid().optional(),active:z.boolean().optional()}).parse(req.body);const old=await q('SELECT * FROM staff WHERE id=$1',[req.params.id]);if(!old.rows[0])return res.status(404).json({ok:false,error:'Staff tidak ditemukan'});const officeId=s.officeId??old.rows[0].office_id;if(!canOffice(req.user,officeId))return res.status(403).json({ok:false,error:'Forbidden'});const r=await q('UPDATE staff SET staff_code=COALESCE($1,staff_code),name=COALESCE($2,name),office_id=$3,active=COALESCE($4,active) WHERE id=$5 RETURNING *',[s.staffCode??null,s.name??null,officeId,s.active??null,req.params.id]);await audit(req,'UPDATE_STAFF',old.rows[0].staff_code,{after:r.rows[0]});res.json({ok:true,item:r.rows[0]});}));

app.get('/api/audit',requireAuth,requireRole('SUPER_ADMIN','ADMIN'),asyncH(async(req,res)=>{const r=await q('SELECT a.*,u.login_id,u.display_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 500');res.json({ok:true,items:r.rows});}));
app.get('/api/users',requireAuth,requireRole('SUPER_ADMIN'),asyncH(async(req,res)=>{const r=await q('SELECT u.id,u.login_id,u.display_name,u.role,u.office_id,u.active,u.created_at,u.last_login_at,o.name office_name FROM users u LEFT JOIN offices o ON o.id=u.office_id ORDER BY u.created_at');res.json({ok:true,items:r.rows});}));
app.post('/api/users',requireAuth,requireRole('SUPER_ADMIN'),asyncH(async(req,res)=>{const bcrypt=(await import('bcryptjs')).default;const s=z.object({loginId:z.string().min(3).max(100),password:z.string().min(8).max(200),displayName:z.string().min(1).max(200),role:z.enum(['SUPER_ADMIN','ADMIN','SUPERVISOR','VIEWER']),officeId:z.string().uuid().nullable().optional()}).parse(req.body);const hash=await bcrypt.hash(s.password,12);const r=await q('INSERT INTO users(login_id,password_hash,display_name,role,office_id) VALUES($1,$2,$3,$4,$5) RETURNING id,login_id,display_name,role,office_id,active,created_at',[s.loginId,hash,s.displayName,s.role,s.officeId||null]);await audit(req,'CREATE_USER',s.loginId,{role:s.role});res.json({ok:true,item:r.rows[0]});}));

io.on('connection',socket=>{socket.on('watchDevice',id=>{if(typeof id==='string')socket.join(`device:${id}`);});socket.on('unwatchDevice',id=>{if(typeof id==='string')socket.leave(`device:${id}`);});});
setInterval(async()=>{try{const r=await q("UPDATE devices SET status='OFFLINE',current_app=NULL,current_title=NULL WHERE COALESCE(user_last_seen,last_seen)<now()-interval '180 seconds' AND (system_last_seen IS NULL OR system_last_seen<now()-interval '180 seconds') AND status<>'OFFLINE' RETURNING id");if(r.rowCount)io.emit('fleet.changed',{offline:r.rowCount});}catch(e){console.error('offline sweep',e.message)}},30000).unref();
setInterval(async()=>{try{const days=Math.max(7,Number(process.env.RAW_RETENTION_DAYS||90));await q(`DELETE FROM activity_events WHERE occurred_at < now() - ($1 || ' days')::interval`,[days]);}catch(e){console.error('retention sweep',e.message)}},6*60*60*1000).unref();
app.use((err,req,res,next)=>{console.error(err);if(err?.name==='ZodError')return res.status(400).json({ok:false,error:'Validation error',detail:err.issues});if(err?.code==='23505')return res.status(409).json({ok:false,error:'Data sudah digunakan / duplikat'});res.status(500).json({ok:false,error:'Internal server error'});});
const port=Number(process.env.PORT||8080);server.listen(port,'0.0.0.0',()=>console.log(`Staff Monitor listening on :${port}`));
process.on('SIGTERM',async()=>{server.close();await pool.end();process.exit(0)});
